### PR TITLE
Gc signup page

### PR DESCRIPTION
**Pull request by gchodancar19**

### CODE REVIEW

**Comment by gchodancar19** [comment]
My signup page does not work on xampp but it might work on plesk.

**Comment by Jforjo** [comment]
Finish your login page pull request first.

**Comment by chrisn02** [comment]
The signup page does not currently work as I am greeted with an error when I attempt to create a user, please remember to only create a pull request for code that is confirmed to be finished and working as intended. Also, same as mentioned above, I think you should finish the code for the login page and get that pull request finished before working on this one.

**Comment by Jforjo** [comment]
> The signup page does not currently work as I am greeted with an error when I attempt to create a user, please remember to only create a pull request for code that is confirmed to be finished and working as intended. Also, same as mentioned above, I think you should finish the code for the login page and get that pull request finished before working on this one.

Try
```php
do {
    $userID = bin2hex(random_bytes(16));
} while (CheckUserIDExists($userID));
```
You might not have a function called "CheckUserIDExists", so just remove the entire do while loop but keep the `$userID = bin2hex(random_bytes(16));`

**Comment by gchodancar19** [comment]
My teams members are aware that why I have done this pull request.

**Review by Jforjo — APPROVED** [review]

**Review by chrisn02 — APPROVED** [review]
You are able to login and create a user, and styling has been improved. Looks good

**Pull request merged**
