### PR TITLE
CN General Fixes

### PR DESCRIPTION
**Pull request by chrisn02**
Have made some general fixes to my code. This includes making the pages more mobile friendly, removing unnecessary code, adding error handling. There may be some redirect errors due to routing, but I have fixed what I could find. Let me know if you spot any more redirect errors. Check commits for full list of fixes

### CODE REVIEW

**Review by Jforjo — APPROVED** [review]
Everything looks good.

**Review by Jforjo — APPROVED** [review]

**Review by Jforjo — APPROVED** [review]

**Comment by Jforjo** [comment]
If you're wondering what the merge conflicts are, take a look here: https://github.com/Jforjo/CSD/commit/7581880d518b1d41bb20d8ce1bea3de812b8049a

**Review by gchodancar19 — APPROVED** [review]
Everything looks good to me as I have reviewed your work yesterday.

**Comment by Jforjo** [comment]
Just delete the 2 files that are causing the merge conflicts. I've already copy and pasted the code from them directly to sudo-main.

**Comment by chrisn02** [comment]
Did you still want me to delete the files causing the merge conflict?

**Comment by chrisn02** [comment]
Sorted now

**Review by Jforjo — APPROVED** [review]
Finally, no merge conflicts...

**Comment by Jforjo** [comment]
This was all because of the ending of a PHP tag "?>" had an extra tab of spacing before it...

**Comment by chrisn02** [comment]
Yeah I noticed that and fixed it in the web editor, strange how that could cause a merge conflict though

**Pull request merged**
