### PR TITLE
JH Student Management

### PR DESCRIPTION
**Pull request by Jforjo**
Created student management page, which first displays a table containing a list of students
Screenshot of student management page
Each button in the "manage" column allows lecturers/admins to edit, delete or promote students. 
Screenshot of the dialog form to edit a user
The table allows lecturers/admins to display a custom amount of students on the page at once, with a custom pagination system at the bottom.

### CODE REVIEW

**Comment by gchodancar19** [comment]
The student management page does looks good but I am not sure whether you required the last field which says state and also the student ID can be made a bit different rather then their full name like either including number or P.Smith.

**Comment by Jforjo** [comment]
> The student management page does looks good but I am not sure whether you required the last field which says state and also the student ID can be made a bit different rather then their full name like either including number or P.Smith.

The state field has been required, which is shown by "Pending" option being lit up.
The student ID is changeable by lecturers and admins, so just change it if you don't like the format (it's only example data).

**Comment by gchodancar19** [comment]
So it's not the actual project page it's jus the format for us to review how it looks.

**Comment by Jforjo** [comment]
> So it's not the actual project page it's jus the format for us to review how it looks.

What do you mean by this?

**Comment by gchodancar19** [comment]
I mean is this how your page looks like.

**Comment by Jforjo** [comment]
> I mean is this how your page looks like.

???????
It looks like how the screenshot above shows...

**Comment by gchodancar19** [comment]
Alright then the format looks good to me.

**Comment by Jforjo** [comment]
> Alright then the format looks good to me.

Then approve the merge request if you feel there are no changes to be made.

**Review by gchodancar19 — APPROVED** [review]

**Review by chrisn02 — APPROVED** [review]
Looks good. I like the layout of the page and the code is well organised with functions and procedures being used as well

**Pull request merged**
