### PR TITLE
JH Admin Dashboard to Sudo Main

### PR DESCRIPTION
**Pull request by Jforjo**
Created HTML/CSS of admin dashboard where both lecturers and senior management will be access their respective management pages. Also, setup the navigation system in place for the individual management pages.

### CODE REVIEW

**Review by chrisn02 — APPROVED** [review]
Good progress. I like the design and general layout of the page

**Review by gchodancar19 — COMMENTED** [review]
Thank you I will have a look.

**Comment by Jforjo** [comment]
Make sure to check the approve button when reviewing if you think this pull request should be pushed to the sudo-main.

**Review by gchodancar19 — APPROVED** [review]
For me it looks good.

**Pull request merged**
