### PR TITLE
CN User Stats Export Functionality

### PR DESCRIPTION
**Pull request by chrisn02**
Have added a button onto the stats page that allows the user to export their data as either CSV or PDF. When the user clicks the export button a modal will popup asking what format they would like to export their data as. If they select CSV then a CSV file will be downloaded and it will display all the data about each completed quiz. If they select PDF then a PDF file will be downloaded. The PDF file was generated using the TCPDF library and highlights the highest scoring quiz in green and the lowest scoring in red. The filenames are formatted as follows: Chris_Stats_24Mar2024.csv

image
image
image
 CSV file contents as viewed in Excel
image PDF file which highlights highest and lowest scoring quizzes

### CODE REVIEW

**Review by Jforjo — APPROVED** [review]
Cool. Although, I don't particularly like, or see the use of, highlighting the highest and lowest scoring tests, especially how the black text inside is a little harder to read. Maybe you could give the user an option to order the tests based on the score instead of the datetime it was completed, which is what I assume it is now. You don't have to give them the option though, but I believe students would find ordering by score, or points, by default to be more beneficial for them. Up to you though.

**Comment by chrisn02** [comment]
Yeah true. I only added the highlighting the best and worst scores as it was mentioned in the brief, but might redo the way it looks and also give users the choice to order based on their scores

**Review by gchodancar19 — APPROVED** [review]
Only the above four titles need to be bigger as it is a bit difficult to read otherwise it looks fine to me.

**Comment by chrisn02** [comment]
Yeah, that's something I will probably work on

**Pull request merged**
